name: 'Github PR Magic'
description: 'Automatically reviewing and approving PRs'
author: 'Darrell Richards'
inputs:
  github_token:
    description: 'Github token'
    required: true
  excluded_files:
    description: 'Files to exclude from review'
    required: false
    default: 'node_modules, package-lock.json, yarn.lock'
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  openai_model:
    description: 'OpenAI model to use (e.g., gpt-4, davinci)'
    required: false
    default: 'gpt-4'
  review_code:
    description: 'Review code'
    required: false
    default: true
  generate_summary:
    description: 'Generates Pull Request summary based on git diff and code changes'
    required: false
    default: false
  overall_code_review:
    description: 'Overall code review as a comment'
    required: false
    default: false
runs:
  using: 'node20'
  main: 'lib/index.js'