name: 'Pull Request Magic'
description: 'Pull Request Magic enables you to streamline your workflow by automating Pull Request Reviews, crafting Pull Request Descriptions, and even auto-approving Pull Requests—all seamlessly integrated with Github Actions. '
author: 'Darrell Richards'
inputs:
  github_token:
    description: 'Github Token for PR approval and code review.'
    required: true
  excluded_files:
    description: 'A comma separated list of files to exclude from code review.'
    required: false
    default: "node_modules, package-lock.json, yarn.lock"
  openai_api_key:
    description: 'OpenAI API Key for code review and approval.'
    required: true
  openai_model:
    description: 'OpenAI model to use (e.g., gpt-4, davinci).'
    required: false
    default: 'gpt-4'
  review_code:
    description: 'Provides code review as a comment line by line.'
    required: false
    default: true
  generate_summary:
    description: 'Generates Pull Request summary based on git diff and code changes'
    required: false
    default: false
  overall_code_review:
    description: 'Provides overall code review as a comment (Overview, Updates and Enhancements, Recommendations).'
    required: false
    default: false
runs:
  using: 'node20'
  main: 'lib/index.js'