name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    ai_code_review:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - uses: actions/setup-node@v4
            with:
              node-version: 18
          - name: Install dependencies
            run: npm install
          - name: Build Code
            run: npm run build
          - name: Run Custom Action
            uses: ./
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              pr-number: ${{ github.event.number }}
              openai_api_key: ${{ secrets.OPEN_AI_KEY }}
              openai_model: 'gpt-4'
              review_code: true
              expluded_files: 'node_modules, package.json, package-lock.json'
